-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE EXTENSION IF NOT EXISTS vector;
--
-- ALTER TABLE itap.identities
--     ADD COLUMN IF NOT EXISTS "embedding" vector(512);
