logLevel: info
logDestinations: [stdout]

api: yes
apiAddress: :9997

rtsp: yes
rtspAddress: :8554

webrtc: no

hls: yes
hlsAddress: :8888
hlsAlwaysRemux: yes
hlsSegmentCount: 7
hlsSegmentDuration: 1s
hlsAllowOrigin: '*'

paths:
  entrance:
    source: publisher
    runOnInit: ffmpeg -re -stream_loop -1 -i /videos/entrance.mp4 -c copy -f rtsp rtsp://localhost:8554/entrance
    runOnInitRestart: yes
  lobby:
    source: publisher
    runOnInit: ffmpeg -re -stream_loop -1 -i /videos/lobby.mp4 -c copy -f rtsp rtsp://localhost:8554/lobby
    runOnInitRestart: yes
  serverroom:
    source: publisher
    runOnInit: ffmpeg -re -stream_loop -1 -i /videos/serverroom.mp4 -c copy -f rtsp rtsp://localhost:8554/serverroom
    runOnInitRestart: yes
  warehouse:
    source: publisher
    runOnInit: ffmpeg -re -stream_loop -1 -i /videos/warehouse.mp4 -c copy -f rtsp rtsp://localhost:8554/warehouse
    runOnInitRestart: yes
